name: graduation
description: "food mobile application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  logger: ^2.4.0
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image_cropper: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Upgraded to latest lints

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/sample_recipe1.png
    - assets/sample_recipe2.png
    - assets/chatbot_icon.png
    - assets/camera_icon.png
    - assets/profile.png
